---
- name: builder env server
  hosts: web
  become: yes

  roles: 
   - docker_works
   - dockerhubconn
   - dockerenvo

- name: runner env server
  hosts: builder
  become: yes

  roles:
   - docker_host
   - dockerhubconn
   - dockerenvo