---
- name: web-server configuration
  hosts: web
  become: yes

  roles: 
   - common
   - webserver
   - security

- name: db configuration
  hosts: builder
  become: yes

  roles:
   - common
   - security 